server:
  port: 8080

spring:
  amqp:
    deserialization:
      trust:
        all: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: theanh199405023@gmail.com
    password: lbwcahcnaealcyzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_db
    username: root
    password: Theanh@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
